imports:
  - php
filter:
  excluded_paths: [vendor/*, tests/*, app/*, bin/*, library/*, fixture/*]

tools:
  # Copy/Paste Detector
  php_cpd: true

  # Metrics
  php_pdepend: true

  # Some Metrics + Bug Detection/Auto-Fixes
  php_analyzer: true

  php_mess_detector:
    enabled: true
    extensions:
      - php
    filter:
      excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'app/*'
        - 'bin/*'
        - 'library/*'
        - 'fixture/*'
      paths: {  }
    config:
      ruleset: null
      code_size_rules:
        cyclomatic_complexity: true
        npath_complexity: true
        excessive_method_length: true
        excessive_class_length: true
        excessive_parameter_list: true
        excessive_public_count: true
        too_many_fields: true
        too_many_methods: true
        excessive_class_complexity: true
      design_rules:
        exit_expression: true
        eval_expression: true
        goto_statement: true
        number_of_class_children: true
        depth_of_inheritance: true
        coupling_between_objects: true
      unused_code_rules:
        unused_private_field: true
        unused_local_variable: true
        unused_private_method: true
        unused_formal_parameter: true
      naming_rules:
        short_variable: true
        long_variable: true
        short_method: true
        constructor_conflict: true
        constant_naming: true
        boolean_method_name: false
      controversial_rules:
        superglobals: true
        camel_case_class_name: true
        camel_case_property_name: true
        camel_case_method_name: true
        camel_case_parameter_name: true
        camel_case_variable_name: true
    path_configs: {  }

  php_cs_fixer:
    config: { level: psr2 }

  php_code_sniffer:
    config:
      standard: PSR2

  php_code_coverage: true