language: php

php:
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer install --prefer-dist --dev
  - vendor/bin/phpcs --standard=PSR2 --extensions=php src tests

after_script:
  - /bin/bash -x ensureCoverage.sh coverage.text